name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the MetaDetector Project! Be mindful that all tests are implemented and run before pushing code. Pull regularly to avoid merge conflicts.'
        pr-message: 'Welcome to the MetaDetector Project!'
